apiVersion: apps/v1
kind: Deployment
metadata:
  name: h8-v1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: h8-v1
  template:
    metadata:
      labels:
        app: h8-v1
    spec:
      containers:
        - name: h8-v1-container
          image: rona03/homework8image:1.0
          ports:
            - containerPort: 80
