apiVersion: apps/v1
kind: Deployment
metadata:
  name: h8-v2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: h8-v2
  template:
    metadata:
      labels:
        app: h8-v2
    spec:
      containers:
        - name: h8-v2-container
          image: rona03/homework8image:2.0
          ports:
            - containerPort: 80
