apiVersion: v1
kind: Service
metadata:
  name: emqx-headless
spec:
  clusterIP: None  # makes it headless
  selector:
    app: emqx
  ports:
    - port: 1883
      name: mqtt
    - port: 8083
      name: websocket
    - port: 18083
      name: dashboard
    - port: 4370
      name: cluster
