apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emqx
spec:
  serviceName: emqx-headless
  replicas: 3
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:5.0.25
        ports:
        - containerPort: 1883 # MQTT port
        - containerPort: 8083 # WebSocket
        - containerPort: 18083 # Dashboard
        - containerPort: 4370 # Cluster port
        envFrom:
        - configMapRef:
            name: emqx-config
        - secretRef:
            name: emqx-cookie
        volumeMounts:
        - name: emqx-data
          mountPath: /opt/emqx/data
  volumeClaimTemplates:
  - metadata:
      name: emqx-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: hostpath
      resources:
        requests:
          storage: 500Mi
